{
	"about": "https://jvndb.jvn.jp/ja/contents/2023/JVNDB-2023-010122.html",
	"title": "mage の Python 用 mage-ai における重要な機能に対する認証の欠如に関する脆弱性",
	"link": "https://jvndb.jvn.jp/ja/contents/2023/JVNDB-2023-010122.html",
	"description": "mage の Python 用 mage-ai には、重要な機能に対する認証の欠如に関する脆弱性が存在します。",
	"identifier": "JVNDB-2023-010122",
	"references": [
		{
			"text": "https://www.cve.org/CVERecord?id=CVE-2023-31143",
			"source": "CVE",
			"id": "CVE-2023-31143"
		},
		{
			"text": "https://nvd.nist.gov/vuln/detail/CVE-2023-31143",
			"source": "NVD",
			"id": "CVE-2023-31143"
		},
		{
			"text": "https://github.com/mage-ai/mage-ai/commit/f63cd00f6a3be372397d37a4c9a49bfaf50d7650",
			"source": "関連文書",
			"id": "github.com (f63cd00f6a3be372397d37a4c9a49bfaf50d7650)"
		},
		{
			"text": "https://github.com/mage-ai/mage-ai/security/advisories/GHSA-c6mm-2g84-v4m7",
			"source": "関連文書",
			"id": "github.com (GHSA-c6mm-2g84-v4m7)"
		},
		{
			"text": "https://cwe.mitre.org/data/definitions/306.html",
			"id": "CWE-306",
			"title": "重要な機能に対する認証の欠如(CWE-306)"
		}
	],
	"cpe": [
		{
			"text": "cpe:/a:mage:mage-ai",
			"version": "2.2",
			"vendor": "mage",
			"product": "mage-ai"
		}
	],
	"cvss": [
		{
			"version": "3.0",
			"score": "9.8",
			"type": "Base",
			"severity": "Critical",
			"vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H"
		}
	],
	"date": "2023-12-08T10:47+09:00",
	"issued": "2023-12-08T10:47+09:00",
	"modified": "2023-12-08T10:47+09:00"
}
