{
	"about": "https://jvndb.jvn.jp/ja/contents/2023/JVNDB-2023-015970.html",
	"title": "Python Software Foundation の Python Pillow におけるリソースの枯渇に関する脆弱性",
	"link": "https://jvndb.jvn.jp/ja/contents/2023/JVNDB-2023-015970.html",
	"description": "Python Software Foundation の Python Pillow には、リソースの枯渇に関する脆弱性が存在します。",
	"identifier": "JVNDB-2023-015970",
	"references": [
		{
			"text": "https://www.cve.org/CVERecord?id=CVE-2023-44271",
			"source": "CVE",
			"id": "CVE-2023-44271"
		},
		{
			"text": "https://nvd.nist.gov/vuln/detail/CVE-2023-44271",
			"source": "NVD",
			"id": "CVE-2023-44271"
		},
		{
			"text": "https://devhub.checkmarx.com/cve-details/CVE-2023-44271/",
			"source": "関連文書",
			"id": "devhub.checkmarx.com (CVE-2023-44271)"
		},
		{
			"text": "https://github.com/python-pillow/Pillow/commit/1fe1bb49c452b0318cad12ea9d97c3bef188e9a7",
			"source": "関連文書",
			"id": "github.com (1fe1bb49c452b0318cad12ea9d97c3bef188e9a7)"
		},
		{
			"text": "https://github.com/python-pillow/Pillow/pull/7244",
			"source": "関連文書",
			"id": "github.com (pull/7244)"
		},
		{
			"text": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/N2JOEDUJDQLCUII2LQYZYSM7RJL2I3P4/",
			"source": "関連文書",
			"id": "lists.fedoraproject.org (N2JOEDUJDQLCUII2LQYZYSM7RJL2I3P4)"
		},
		{
			"text": "https://cwe.mitre.org/data/definitions/400.html",
			"id": "CWE-400",
			"title": "リソースの枯渇(CWE-400)"
		}
	],
	"cpe": [
		{
			"text": "cpe:/a:python:pillow",
			"version": "2.2",
			"vendor": "Python Software Foundation",
			"product": "Python Pillow"
		}
	],
	"cvss": [
		{
			"version": "3.0",
			"score": "7.5",
			"type": "Base",
			"severity": "High",
			"vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
		}
	],
	"date": "2023-12-28T15:16+09:00",
	"issued": "2023-12-28T15:16+09:00",
	"modified": "2023-12-28T15:16+09:00"
}
