{
  "about": "https://jvndb.jvn.jp/ja/contents/2014/JVNDB-2014-005623.html",
  "title": "pip におけるサービス運用妨害 (DoS) の脆弱性",
  "link": "https://jvndb.jvn.jp/ja/contents/2014/JVNDB-2014-005623.html",
  "description": "pip には、サービス運用妨害 (パッケージインストールの阻止) 状態にされる脆弱性が存在します。",
  "identifier": "JVNDB-2014-005623",
  "references": [
    {
      "text": "http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2014-8991",
      "source": "CVE",
      "id": "CVE-2014-8991"
    },
    {
      "text": "http://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2014-8991",
      "source": "NVD",
      "id": "CVE-2014-8991"
    },
    {
      "text": "https://jvndb.jvn.jp/ja/cwe/CWE-264.html",
      "id": "CWE-264",
      "title": "認可・権限・アクセス制御(CWE-264)"
    }
  ],
  "cpe": [
    {
      "text": "cpe:/a:python:pip",
      "version": "2.2",
      "vendor": "Python Software Foundation",
      "product": "pip"
    }
  ],
  "cvss": [
    {
      "version": "2.0",
      "score": "2.1",
      "type": "Base",
      "severity": "Low",
      "vector": "AV:L/AC:L/Au:N/C:N/I:N/A:P"
    }
  ],
  "date": "2015-07-31T11:07+09:00",
  "issued": "2014-11-26T15:46+09:00",
  "modified": "2015-07-31T11:07+09:00"
}
