{
  "about": "https://jvndb.jvn.jp/ja/contents/2017/JVNDB-2017-011156.html",
  "title": "Panda Global Protection におけるバッファエラーの脆弱性",
  "link": "https://jvndb.jvn.jp/ja/contents/2017/JVNDB-2017-011156.html",
  "description": "Panda Global Protection には、バッファエラーの脆弱性が存在します。",
  "identifier": "JVNDB-2017-011156",
  "references": [
    {
      "text": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2017-17683",
      "source": "CVE",
      "id": "CVE-2017-17683"
    },
    {
      "text": "https://nvd.nist.gov/vuln/detail/CVE-2017-17683",
      "source": "NVD",
      "id": "CVE-2017-17683"
    },
    {
      "text": "https://github.com/k0keoyo/Driver-Loaded-PoC/tree/master/Panda-Antivirus/Panda_Security_Antivirus_0xb3702c04_",
      "source": "関連文書",
      "id": "Driver-Loaded-PoC/Panda-Antivirus/Panda_Security_Antivirus_0xb3702c04_/"
    },
    {
      "text": "https://jvndb.jvn.jp/ja/cwe/CWE-119.html",
      "id": "CWE-119",
      "title": "バッファエラー(CWE-119)"
    }
  ],
  "cpe": [
    {
      "text": "cpe:/a:pandasecurity:panda_global_protection",
      "version": "2.2",
      "vendor": "Panda Security",
      "product": "Panda Global Protection"
    }
  ],
  "cvss": [
    {
      "version": "2.0",
      "score": "7.8",
      "type": "Base",
      "severity": "High",
      "vector": "AV:N/AC:L/Au:N/C:N/I:N/A:C"
    },
    {
      "version": "3.0",
      "score": "7.5",
      "type": "Base",
      "severity": "High",
      "vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
    }
  ],
  "date": "2018-01-10T11:49+09:00",
  "issued": "2018-01-10T11:49+09:00",
  "modified": "2018-01-10T11:49+09:00"
}
