{
	"about": "https://jvndb.jvn.jp/ja/contents/2017/JVNDB-2017-002956.html",
	"title": "Django におけるオープンリダイレクトの脆弱性",
	"link": "https://jvndb.jvn.jp/ja/contents/2017/JVNDB-2017-002956.html",
	"description": "Django には、オープンリダイレクトの脆弱性が存在します。",
	"identifier": "JVNDB-2017-002956",
	"references": [
		{
			"text": "http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2017-7233",
			"source": "CVE",
			"id": "CVE-2017-7233"
		},
		{
			"text": "https://nvd.nist.gov/vuln/detail/CVE-2017-7233",
			"source": "NVD",
			"id": "CVE-2017-7233"
		},
		{
			"text": "https://cwe.mitre.org/data/definitions/601.html",
			"id": "CWE-601",
			"title": "オープンリダイレクト(CWE-601)"
		}
	],
	"cpe": [
		{
			"text": "cpe:/a:djangoproject:django",
			"version": "2.2",
			"vendor": "Django Software Foundation",
			"product": "Django"
		}
	],
	"cvss": [
		{
			"version": "2.0",
			"score": "5.8",
			"type": "Base",
			"severity": "Medium",
			"vector": "AV:N/AC:M/Au:N/C:P/I:P/A:N"
		},
		{
			"version": "3.0",
			"score": "6.1",
			"type": "Base",
			"severity": "Medium",
			"vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N"
		}
	],
	"date": "2017-05-09T17:06+09:00",
	"issued": "2017-05-09T17:06+09:00",
	"modified": "2017-05-09T17:06+09:00"
}
