{
	"about": "https://jvndb.jvn.jp/ja/contents/2020/JVNDB-2020-002529.html",
	"title": "GitLab における権限管理に関する脆弱性",
	"link": "https://jvndb.jvn.jp/ja/contents/2020/JVNDB-2020-002529.html",
	"description": "GitLab には、権限管理に関する脆弱性が存在します。",
	"identifier": "JVNDB-2020-002529",
	"references": [
		{
			"text": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-8113",
			"source": "CVE",
			"id": "CVE-2020-8113"
		},
		{
			"text": "https://nvd.nist.gov/vuln/detail/CVE-2020-8113",
			"source": "NVD",
			"id": "CVE-2020-8113"
		},
		{
			"text": "https://bugs.chromium.org/p/project-zero/issues/detail?id=1992",
			"source": "関連文書",
			"id": "Issue 1992: (usersctp: out-of-bounds reads in sctp_load_addresses_from_init)"
		},
		{
			"text": "https://cwe.mitre.org/data/definitions/269.html",
			"id": "CWE-269",
			"title": "不適切な権限管理(CWE-269)"
		}
	],
	"cpe": [
		{
			"text": "cpe:/a:gitlab:gitlab",
			"version": "2.2",
			"vendor": "GitLab.org",
			"product": "GitLab"
		}
	],
	"cvss": [
		{
			"version": "2.0",
			"score": "7.5",
			"type": "Base",
			"severity": "High",
			"vector": "AV:N/AC:L/Au:N/C:P/I:P/A:P"
		},
		{
			"version": "3.0",
			"score": "9.8",
			"type": "Base",
			"severity": "Critical",
			"vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H"
		}
	],
	"date": "2020-03-18T15:06+09:00",
	"issued": "2020-03-18T15:06+09:00",
	"modified": "2020-03-18T15:06+09:00"
}
