{
  "about": "https://jvndb.jvn.jp/ja/contents/2020/JVNDB-2020-005296.html",
  "title": "Apache log4net における XML 外部エンティティの脆弱性",
  "link": "https://jvndb.jvn.jp/ja/contents/2020/JVNDB-2020-005296.html",
  "description": "Apache log4net には、XML 外部エンティティの脆弱性が存在します。",
  "identifier": "JVNDB-2020-005296",
  "references": [
    {
      "text": "https://jvn.jp/ta/JVNTA94851885/",
      "source": "JVN",
      "id": "JVNTA#94851885"
    },
    {
      "text": "http://jvn.jp/vu/JVNVU97972484/index.html",
      "source": "JVN",
      "id": "JVNVU#97972484"
    },
    {
      "text": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2018-1285",
      "source": "CVE",
      "id": "CVE-2018-1285"
    },
    {
      "text": "https://nvd.nist.gov/vuln/detail/CVE-2018-1285",
      "source": "NVD",
      "id": "CVE-2018-1285"
    },
    {
      "text": "https://www.cisa.gov/news-events/ics-medical-advisories/icsma-23-194-01",
      "source": "ICS-CERT ADVISORY",
      "id": "ICSMA-23-194-01"
    },
    {
      "text": "https://cwe.mitre.org/data/definitions/611.html",
      "id": "CWE-611",
      "title": "XML 外部エンティティ参照の不適切な制限(CWE-611)"
    }
  ],
  "cpe": [
    {
      "text": "cpe:/a:apache:log4net",
      "version": "2.2",
      "vendor": "Apache Software Foundation",
      "product": "Apache log4net"
    }
  ],
  "cvss": [
    {
      "version": "2.0",
      "score": "7.5",
      "type": "Base",
      "severity": "High",
      "vector": "AV:N/AC:L/Au:N/C:P/I:P/A:P"
    },
    {
      "version": "3.0",
      "score": "9.8",
      "type": "Base",
      "severity": "Critical",
      "vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H"
    }
  ],
  "date": "2023-07-20T13:08+09:00",
  "issued": "2020-06-11T15:39+09:00",
  "modified": "2023-07-20T13:08+09:00"
}
