{
	"about": "https://jvndb.jvn.jp/ja/contents/2020/JVNDB-2020-009121.html",
	"title": "faye-websocket における証明書検証に関する脆弱性",
	"link": "https://jvndb.jvn.jp/ja/contents/2020/JVNDB-2020-009121.html",
	"description": "faye-websocket には、証明書検証に関する脆弱性が存在します。",
	"identifier": "JVNDB-2020-009121",
	"references": [
		{
			"text": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-15133",
			"source": "CVE",
			"id": "CVE-2020-15133"
		},
		{
			"text": "https://nvd.nist.gov/vuln/detail/CVE-2020-15133",
			"source": "NVD",
			"id": "CVE-2020-15133"
		},
		{
			"text": "https://cwe.mitre.org/data/definitions/295.html",
			"id": "CWE-295",
			"title": "不正な証明書検証(CWE-295)"
		}
	],
	"cpe": [
		{
			"text": "cpe:/a:faye_project:faye-websocket",
			"version": "2.2",
			"vendor": "Faye project",
			"product": "faye-websocket"
		}
	],
	"cvss": [
		{
			"version": "2.0",
			"score": "5.8",
			"type": "Base",
			"severity": "Medium",
			"vector": "AV:N/AC:M/Au:N/C:P/I:P/A:N"
		},
		{
			"version": "3.0",
			"score": "8.7",
			"type": "Base",
			"severity": "High",
			"vector": "CVSS:3.0/AV:N/AC:H/PR:N/UI:N/S:C/C:H/I:H/A:N"
		}
	],
	"date": "2020-10-20T17:13+09:00",
	"issued": "2020-10-20T17:13+09:00",
	"modified": "2020-10-20T17:13+09:00"
}
