{
	"about": "https://jvndb.jvn.jp/ja/contents/2020/JVNDB-2020-018136.html",
	"title": "Exiv2 project の Exiv2 における境界外書き込みに関する脆弱性",
	"link": "https://jvndb.jvn.jp/ja/contents/2020/JVNDB-2020-018136.html",
	"description": "Exiv2 project の Exiv2 には、境界外書き込みに関する脆弱性が存在します。",
	"identifier": "JVNDB-2020-018136",
	"references": [
		{
			"text": "https://www.cve.org/CVERecord?id=CVE-2020-18831",
			"source": "CVE",
			"id": "CVE-2020-18831"
		},
		{
			"text": "https://nvd.nist.gov/vuln/detail/CVE-2020-18831",
			"source": "NVD",
			"id": "CVE-2020-18831"
		},
		{
			"text": "https://github.com/Exiv2/exiv2/issues/828",
			"source": "関連文書",
			"id": "github.com (issues/828)"
		},
		{
			"text": "https://cwe.mitre.org/data/definitions/787.html",
			"id": "CWE-787",
			"title": "境界外書き込み(CWE-787)"
		}
	],
	"cpe": [
		{
			"text": "cpe:/a:exiv2:exiv2",
			"version": "2.2",
			"vendor": "Exiv2 project",
			"product": "Exiv2"
		}
	],
	"cvss": [
		{
			"version": "3.0",
			"score": "7.8",
			"type": "Base",
			"severity": "High",
			"vector": "CVSS:3.0/AV:L/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H"
		}
	],
	"date": "2024-01-23T11:00+09:00",
	"issued": "2024-01-23T11:00+09:00",
	"modified": "2024-01-23T11:00+09:00"
}
