{
	"about": "https://jvndb.jvn.jp/ja/contents/2020/JVNDB-2020-011817.html",
	"title": "Xen におけるバッファエラーの脆弱性",
	"link": "https://jvndb.jvn.jp/ja/contents/2020/JVNDB-2020-011817.html",
	"description": "Xen には、バッファエラーの脆弱性が存在します。\r\n",
	"identifier": "JVNDB-2020-011817",
	"references": [
		{
			"text": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-25597",
			"source": "CVE",
			"id": "CVE-2020-25597"
		},
		{
			"text": "https://nvd.nist.gov/vuln/detail/CVE-2020-25597",
			"source": "NVD",
			"id": "CVE-2020-25597"
		},
		{
			"text": "https://jvndb.jvn.jp/ja/cwe/CWE-119.html",
			"id": "CWE-119",
			"title": "バッファエラー(CWE-119)"
		}
	],
	"cpe": [
		{
			"text": "cpe:/o:xen:xen",
			"version": "2.2",
			"vendor": "Xen プロジェクト",
			"product": "Xen"
		}
	],
	"cvss": [
		{
			"version": "2.0",
			"score": "6.1",
			"type": "Base",
			"severity": "Medium",
			"vector": "AV:L/AC:L/Au:N/C:P/I:P/A:C"
		},
		{
			"version": "3.0",
			"score": "6.5",
			"type": "Base",
			"severity": "Medium",
			"vector": "CVSS:3.0/AV:L/AC:L/PR:L/UI:N/S:C/C:N/I:N/A:H"
		}
	],
	"date": "2021-04-15T16:22+09:00",
	"issued": "2021-04-15T16:22+09:00",
	"modified": "2021-04-15T16:22+09:00"
}
