{
	"about": "https://jvndb.jvn.jp/ja/contents/2022/JVNDB-2022-019482.html",
	"title": "GitLab.org の GitLab における例外的な状態の処理に関する脆弱性",
	"link": "https://jvndb.jvn.jp/ja/contents/2022/JVNDB-2022-019482.html",
	"description": "GitLab.org の GitLab には、例外的な状態の処理に関する脆弱性が存在します。",
	"identifier": "JVNDB-2022-019482",
	"references": [
		{
			"text": "https://www.cve.org/CVERecord?id=CVE-2022-3279",
			"source": "CVE",
			"id": "CVE-2022-3279"
		},
		{
			"text": "https://nvd.nist.gov/vuln/detail/CVE-2022-3279",
			"source": "NVD",
			"id": "CVE-2022-3279"
		},
		{
			"text": "https://gitlab.com/gitlab-org/cves/-/blob/master/2022/CVE-2022-3279.json",
			"source": "関連文書",
			"id": "gitlab.com (CVE-2022-3279.json)"
		},
		{
			"text": "https://cwe.mitre.org/data/definitions/755.html",
			"id": "CWE-755",
			"title": "例外的な状態における不適切な処理(CWE-755)"
		}
	],
	"cpe": [
		{
			"text": "cpe:/a:gitlab:gitlab",
			"version": "2.2",
			"vendor": "GitLab.org",
			"product": "GitLab"
		}
	],
	"cvss": [
		{
			"version": "3.0",
			"score": "6.5",
			"type": "Base",
			"severity": "Medium",
			"vector": "CVSS:3.0/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H"
		}
	],
	"date": "2023-10-25T17:15+09:00",
	"issued": "2023-10-25T17:15+09:00",
	"modified": "2023-10-25T17:15+09:00"
}
