{
  "about": "https://jvndb.jvn.jp/ja/contents/2021/JVNDB-2021-006496.html",
  "title": "libgetdata における解放済みメモリの使用に関する脆弱性",
  "link": "https://jvndb.jvn.jp/ja/contents/2021/JVNDB-2021-006496.html",
  "description": "libgetdata には、解放済みメモリの使用に関する脆弱性が存在します。",
  "identifier": "JVNDB-2021-006496",
  "references": [
    {
      "text": "https://www.cve.org/CVERecord?id=CVE-2021-20204",
      "source": "CVE",
      "id": "CVE-2021-20204"
    },
    {
      "text": "https://nvd.nist.gov/vuln/detail/CVE-2021-20204",
      "source": "NVD",
      "id": "CVE-2021-20204"
    },
    {
      "text": "https://bugzilla.redhat.com/show_bug.cgi?id=1956348",
      "source": "関連文書",
      "id": "Bug 1956348 (CVE-2021-20204) - CVE-2021-20204 getdata: Use after free in _GD_Supports() in encoding.c"
    },
    {
      "text": "https://cwe.mitre.org/data/definitions/416.html",
      "id": "CWE-416",
      "title": "解放済みメモリの使用(CWE-416)"
    }
  ],
  "cpe": [
    {
      "text": "cpe:/a:getdata_project:getdata",
      "version": "2.2",
      "vendor": "getdata project",
      "product": "getdata"
    },
    {
      "text": "cpe:/o:debian:debian_linux",
      "version": "2.2",
      "vendor": "Debian",
      "product": "Debian GNU/Linux"
    },
    {
      "text": "cpe:/o:fedoraproject:fedora",
      "version": "2.2",
      "vendor": "Fedora Project",
      "product": "Fedora"
    }
  ],
  "cvss": [
    {
      "version": "2.0",
      "score": "7.5",
      "type": "Base",
      "severity": "High",
      "vector": "AV:N/AC:L/Au:N/C:P/I:P/A:P"
    },
    {
      "version": "3.0",
      "score": "9.8",
      "type": "Base",
      "severity": "Critical",
      "vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H"
    }
  ],
  "date": "2022-01-11T15:02+09:00",
  "issued": "2022-01-11T15:02+09:00",
  "modified": "2022-01-11T15:02+09:00"
}
